# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 49a99985f141758a5f96d07cd36ecd6b2d9c649f1ed6fd697f52a769bb648ffc4bba40268ab0e9c11cbe176c29884665d19c57593943619a2464aa66dc9fc840

test:
  secret_key_base: a1db064ec15f48338563add7d1fdf4bb8d848636f43b664a5658be21af04ffbdabf85bff12529801477d684f29910287cc25e8f9e3b51c12409cf83e459f2894

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
